// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ArticleMobileViewModuleScssNamespace {
  export interface IArticleMobileViewModuleScss {
    articleViewCategories: string;
    articleViewCategory: string;
    articleViewDate: string;
    articleViewImage: string;
    articleViewTitle: string;
    articleViewWrapper: string;
  }
}

declare const ArticleMobileViewModuleScssModule: ArticleMobileViewModuleScssNamespace.IArticleMobileViewModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ArticleMobileViewModuleScssNamespace.IArticleMobileViewModuleScss;
};

export = ArticleMobileViewModuleScssModule;
