// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ArticleDefaultViewModuleScssNamespace {
  export interface IArticleDefaultViewModuleScss {
    articleViewButton: string;
    articleViewCategories: string;
    articleViewCategory: string;
    articleViewContent: string;
    articleViewDate: string;
    articleViewDescription: string;
    articleViewImage: string;
    articleViewLeft: string;
    articleViewTitle: string;
    articleViewTop: string;
  }
}

declare const ArticleDefaultViewModuleScssModule: ArticleDefaultViewModuleScssNamespace.IArticleDefaultViewModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ArticleDefaultViewModuleScssNamespace.IArticleDefaultViewModuleScss;
};

export = ArticleDefaultViewModuleScssModule;
