// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ArticleModuleScssNamespace {
  export interface IArticleModuleScss {
    article: string;
    articleObserver: string;
    articleTimer: string;
    articleWrapper: string;
  }
}

declare const ArticleModuleScssModule: ArticleModuleScssNamespace.IArticleModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ArticleModuleScssNamespace.IArticleModuleScss;
};

export = ArticleModuleScssModule;
