// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ArticleModuleScssNamespace {
  export interface IArticleModuleScss {
    article: string;
    articleButton: string;
    articleCategories: string;
    articleCategory: string;
    articleContent: string;
    articleDate: string;
    articleDescription: string;
    articleImage: string;
    articleLeft: string;
    articleObserver: string;
    articleTimer: string;
    articleTitle: string;
    articleTop: string;
    articleWrapper: string;
    debug: string;
  }
}

declare const ArticleModuleScssModule: ArticleModuleScssNamespace.IArticleModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ArticleModuleScssNamespace.IArticleModuleScss;
};

export = ArticleModuleScssModule;
